[project]
name = "rnd"
version = "0.1.0"
description = "AC Sales & Weather Analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "plotly>=5.15.0",
    "statsmodels>=0.14.0",
    "scipy>=1.11.0",
    "scikit-learn>=1.3.0",
    "tensorflow>=2.13.0",
    "prophet>=1.1.4",
    "pmdarima>=2.0.4",
    "jupyter>=1.0.0",
    "ipykernel>=7.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
]
